disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Home"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Geospatial Communicator"
  copyright = "© {2026} Kiri Carini. All rights reserved."

  [params.author]
  name = "Kiri Carini"
  image = "headshot-alley.png"
  imageQuality = 96
  headline = "Geospatial Communicator"
  bio = "I work at the intersection of GIS, communication, and education."
  links = [
    { linkedin = "https://www.linkedin.com/in/kcarini/" },
    { github = "https://github.com/kcarini" }
  ]
